# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/toye/dev/src/MiAM_robotics/eurobot2021/MainRobotCode/embedded

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/toye/dev/src/MiAM_robotics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toye/dev/src/MiAM_robotics/CMakeFiles /home/toye/dev/src/MiAM_robotics//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toye/dev/src/MiAM_robotics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mainRobotCode

# Build rule for target.
mainRobotCode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mainRobotCode
.PHONY : mainRobotCode

# fast build rule for target.
mainRobotCode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/build
.PHONY : mainRobotCode/fast

eurobot2021/MainRobotCode/common/src/ServoHandler.o: eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.o

.PHONY : eurobot2021/MainRobotCode/common/src/ServoHandler.o

# target to build an object file
eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.o
.PHONY : eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.o

eurobot2021/MainRobotCode/common/src/ServoHandler.i: eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.i

.PHONY : eurobot2021/MainRobotCode/common/src/ServoHandler.i

# target to preprocess a source file
eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.i
.PHONY : eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.i

eurobot2021/MainRobotCode/common/src/ServoHandler.s: eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.s

.PHONY : eurobot2021/MainRobotCode/common/src/ServoHandler.s

# target to generate assembly for a file
eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.s
.PHONY : eurobot2021/MainRobotCode/common/src/ServoHandler.cpp.s

eurobot2021/MainRobotCode/common/src/Strategy.o: eurobot2021/MainRobotCode/common/src/Strategy.cpp.o

.PHONY : eurobot2021/MainRobotCode/common/src/Strategy.o

# target to build an object file
eurobot2021/MainRobotCode/common/src/Strategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/eurobot2021/MainRobotCode/common/src/Strategy.cpp.o
.PHONY : eurobot2021/MainRobotCode/common/src/Strategy.cpp.o

eurobot2021/MainRobotCode/common/src/Strategy.i: eurobot2021/MainRobotCode/common/src/Strategy.cpp.i

.PHONY : eurobot2021/MainRobotCode/common/src/Strategy.i

# target to preprocess a source file
eurobot2021/MainRobotCode/common/src/Strategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/eurobot2021/MainRobotCode/common/src/Strategy.cpp.i
.PHONY : eurobot2021/MainRobotCode/common/src/Strategy.cpp.i

eurobot2021/MainRobotCode/common/src/Strategy.s: eurobot2021/MainRobotCode/common/src/Strategy.cpp.s

.PHONY : eurobot2021/MainRobotCode/common/src/Strategy.s

# target to generate assembly for a file
eurobot2021/MainRobotCode/common/src/Strategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/eurobot2021/MainRobotCode/common/src/Strategy.cpp.s
.PHONY : eurobot2021/MainRobotCode/common/src/Strategy.cpp.s

src/MainLoop.o: src/MainLoop.cpp.o

.PHONY : src/MainLoop.o

# target to build an object file
src/MainLoop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/MainLoop.cpp.o
.PHONY : src/MainLoop.cpp.o

src/MainLoop.i: src/MainLoop.cpp.i

.PHONY : src/MainLoop.i

# target to preprocess a source file
src/MainLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/MainLoop.cpp.i
.PHONY : src/MainLoop.cpp.i

src/MainLoop.s: src/MainLoop.cpp.s

.PHONY : src/MainLoop.s

# target to generate assembly for a file
src/MainLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/MainLoop.cpp.s
.PHONY : src/MainLoop.cpp.s

src/Robot.o: src/Robot.cpp.o

.PHONY : src/Robot.o

# target to build an object file
src/Robot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/Robot.cpp.o
.PHONY : src/Robot.cpp.o

src/Robot.i: src/Robot.cpp.i

.PHONY : src/Robot.i

# target to preprocess a source file
src/Robot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/Robot.cpp.i
.PHONY : src/Robot.cpp.i

src/Robot.s: src/Robot.cpp.s

.PHONY : src/Robot.s

# target to generate assembly for a file
src/Robot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/Robot.cpp.s
.PHONY : src/Robot.cpp.s

src/Robot_Detection.o: src/Robot_Detection.cpp.o

.PHONY : src/Robot_Detection.o

# target to build an object file
src/Robot_Detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/Robot_Detection.cpp.o
.PHONY : src/Robot_Detection.cpp.o

src/Robot_Detection.i: src/Robot_Detection.cpp.i

.PHONY : src/Robot_Detection.i

# target to preprocess a source file
src/Robot_Detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/Robot_Detection.cpp.i
.PHONY : src/Robot_Detection.cpp.i

src/Robot_Detection.s: src/Robot_Detection.cpp.s

.PHONY : src/Robot_Detection.s

# target to generate assembly for a file
src/Robot_Detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/Robot_Detection.cpp.s
.PHONY : src/Robot_Detection.cpp.s

src/Robot_MotionControl.o: src/Robot_MotionControl.cpp.o

.PHONY : src/Robot_MotionControl.o

# target to build an object file
src/Robot_MotionControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/Robot_MotionControl.cpp.o
.PHONY : src/Robot_MotionControl.cpp.o

src/Robot_MotionControl.i: src/Robot_MotionControl.cpp.i

.PHONY : src/Robot_MotionControl.i

# target to preprocess a source file
src/Robot_MotionControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/Robot_MotionControl.cpp.i
.PHONY : src/Robot_MotionControl.cpp.i

src/Robot_MotionControl.s: src/Robot_MotionControl.cpp.s

.PHONY : src/Robot_MotionControl.s

# target to generate assembly for a file
src/Robot_MotionControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/Robot_MotionControl.cpp.s
.PHONY : src/Robot_MotionControl.cpp.s

src/uCListener.o: src/uCListener.cpp.o

.PHONY : src/uCListener.o

# target to build an object file
src/uCListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/uCListener.cpp.o
.PHONY : src/uCListener.cpp.o

src/uCListener.i: src/uCListener.cpp.i

.PHONY : src/uCListener.i

# target to preprocess a source file
src/uCListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/uCListener.cpp.i
.PHONY : src/uCListener.cpp.i

src/uCListener.s: src/uCListener.cpp.s

.PHONY : src/uCListener.s

# target to generate assembly for a file
src/uCListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainRobotCode.dir/build.make CMakeFiles/mainRobotCode.dir/src/uCListener.cpp.s
.PHONY : src/uCListener.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mainRobotCode"
	@echo "... eurobot2021/MainRobotCode/common/src/ServoHandler.o"
	@echo "... eurobot2021/MainRobotCode/common/src/ServoHandler.i"
	@echo "... eurobot2021/MainRobotCode/common/src/ServoHandler.s"
	@echo "... eurobot2021/MainRobotCode/common/src/Strategy.o"
	@echo "... eurobot2021/MainRobotCode/common/src/Strategy.i"
	@echo "... eurobot2021/MainRobotCode/common/src/Strategy.s"
	@echo "... src/MainLoop.o"
	@echo "... src/MainLoop.i"
	@echo "... src/MainLoop.s"
	@echo "... src/Robot.o"
	@echo "... src/Robot.i"
	@echo "... src/Robot.s"
	@echo "... src/Robot_Detection.o"
	@echo "... src/Robot_Detection.i"
	@echo "... src/Robot_Detection.s"
	@echo "... src/Robot_MotionControl.o"
	@echo "... src/Robot_MotionControl.i"
	@echo "... src/Robot_MotionControl.s"
	@echo "... src/uCListener.o"
	@echo "... src/uCListener.i"
	@echo "... src/uCListener.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

